### ISSUE TITLE
Crash after start due to missing init.js resource

### ISSUE THREAD

**Issue by castarco** [klauscfhq/ao#31]
**Describe the bug**

**To Reproduce**

1. Copy the ao 5.6.0 AppImage x86_64 binary to `~/.local/bin/ao`
2. Mark it as executable `chmod ~/.local/bin/ao`
3. Execute the binary: `ao` , or `~/.local/bin/ao`

**Expected behavior**
It should start after the update, but it crashes. More details provided in the following sections.

**Technical Info (please complete the following information)**
 - OS: `Ubuntu 18.04 64 bits`
 - Ao Version: `5.6.0`

Console Output:
```
Error: Cannot find module '/tmp/.mount_aozmTZY6/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```

**Additional context**
- Since I updated to the new version I can't launch Ao anymore.
- The first time I launch the app after the upgrade (upgrade by AppImage binary substitution), I'm asked again to recreate a desktop shortcut (but I had a shortcut before, so it does not make sense).
- Once the shortcut is created, the application crashes  (the output is added to the technical info section). The crash output only appears after the shortcut creation, never before.

**Comment by GeorgHoffmeyer** [comment]
I'm having the same issue

**Comment by castarco** [comment]
Any update on this issue?
