### ISSUE TITLE
Weird startup behavior when ~/Downloads is replaced with symbolic link

### ISSUE THREAD

**Issue by yenson-lau** [klauscfhq/ao#41]
**Describe the bug**
I dual boot between Win10 and Ubuntu and share a storage partition. To facilitate downloads I have a symbolic link for ~/Downloads. This leads to error messages when I start Ao, and has lead to traceback crashes in the past which forces me to reinstall.

**To Reproduce**
Uninstall / reinstall using `snap`, then enter `ao` from command line.

**Expected behavior**
Startup with no error messages.

**Screenshots**
`yenson@XPS15:~$ ao`
`/home/yenson/Downloads was removed, reassigning DOWNLOAD to homedir`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`{ Error: Cannot find module '../screen'`
`    at Module._resolveFilename (module.js:543:15)`
`    at Function.Module._resolveFilename (/snap/ao/10/resources/electron.asar/common/reset-search-paths.js:35:12)`
`    at Function.Module._load (module.js:473:25)`
`    at Module.require (module.js:586:17)`
`    at require (internal/module.js:11:18)`
`    at Object.get [as screen] (/snap/ao/10/resources/electron.asar/browser/api/exports/electron.js:11:16)`
`    at createMainWindow (/snap/ao/10/resources/app.asar/index.js:43:36)`
`    at App.app.on (/snap/ao/10/resources/app.asar/index.js:102:16)`
`    at emitTwo (events.js:131:20)`
`    at App.emit (events.js:214:7) code: 'MODULE_NOT_FOUND' }`

**Technical Info (please complete the following information)**
 - OS: Ubuntu 18.04
 - Ao Version: 5.6.0.

**Additional context**

**Comment by yenson-lau** [comment]
Error messages still show up after recreating ~/Downloads folder, but no other problems.
